// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASBhCiWQfmyHVB9fPFwBCtBbafKrNlWB8',
    appId: '1:1045599588702:android:d702aa2ba09b2f37bbffcf',
    messagingSenderId: '1045599588702',
    projectId: 'al-mullah-asignment',
    storageBucket: 'al-mullah-asignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAam9gKkZt3_g0du1jrmw_F0hh5Se_A5F4',
    appId: '1:1045599588702:ios:903efe5bf58fe7bfbbffcf',
    messagingSenderId: '1045599588702',
    projectId: 'al-mullah-asignment',
    storageBucket: 'al-mullah-asignment.firebasestorage.app',
    iosBundleId: 'com.example.alMullahAsignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAam9gKkZt3_g0du1jrmw_F0hh5Se_A5F4',
    appId: '1:1045599588702:ios:903efe5bf58fe7bfbbffcf',
    messagingSenderId: '1045599588702',
    projectId: 'al-mullah-asignment',
    storageBucket: 'al-mullah-asignment.firebasestorage.app',
    iosBundleId: 'com.example.alMullahAsignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3ZYvTUY1nkYHhBlxOTdd94cG4ak6JdYU',
    appId: '1:1045599588702:web:da2b81fb99f5547dbbffcf',
    messagingSenderId: '1045599588702',
    projectId: 'al-mullah-asignment',
    authDomain: 'al-mullah-asignment.firebaseapp.com',
    storageBucket: 'al-mullah-asignment.firebasestorage.app',
  );
}
